{{- if .Values.certManager.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "stack-tech.fullname" . }}-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.certManager.source.targetRevision }}
    chart: cert-manager
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
{{- end }}
