spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
#  *************
k8s:
  flavor: rke2
longhorn:
  enabled: true
  source:
    targetRevision: v1.6.1
prom2teams:
  source:
    targetRevision: '1.3.4'
  connectors: 
  - teams : "https://charlesandre.webhook.office.com/webhookb2/5c49e775-13d2-4f6d-80b5-ba3f1651ebaf@38e68108-2383-4d82-a4b3-ac423a5e6218/IncomingWebhook/8c89ebe05dff443391f7c465b1ed1dee/dfd76bdb-37d4-4c4c-b907-6ea781954db5"
#  *************
kubePrometheusStack:
  enabled: false
  source:
    targetRevision: '58.0.0'
  prometheus:
    prometheusSpec:
      retention: 24h
      retentionSize: 1GB    
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client         
            resources:
              requests:
                storage: 3Gi
  grafana:
    ingress:
      enabled: false 
      hosts: 
       - grafana.gcatrans.com              
  alertmanager:
    config:
      global:
        smtp_from: "Azure@gcatrans.com"
#  *************
loki:
  enabled: false
  source:
    targetRevision: '5.47.2'
  singleBinary:
    persistence:
      size: 3Gi
  limits_config:
    retention_period: 24h
#  *************
promtail:
  source:
    targetRevision: '6.15.5'
#  *************
tempo:
  enabled: false
  source:
    targetRevision: '1.7.2'
  persistence:
    size: 1Gi
  retention: 24h
#  *************
opentelemetry:
  enabled: false
  source:
    targetRevision: '0.86.2'
  operator:
    enabled: false
  config:
    receivers:
      otlp:
        protocols:
          http:
            cors:
              allowed_origins: ['http://*.gcatrans.com, http://*.gcatrans.com:4200, https://*.gcatrans.com']
otelOperator:
  source:
    targetRevision: '*'
#  *************
certManager:
  enabled: true
  source:
    targetRevision: '1.14.4'
#  *************
neuvector:
  enabled: false
  global:
    cattle:
      clusterName : cluster.local
      clusterId: cluster
  controller:
    pvc:
      storageClass: nfs-client
  manager:
    ingress:
      enabled: true
      host: neuvector.gcatrans.com
  crd:
    source:
      targetRevision: '2.7.3'      
  source:
    targetRevision: '2.7.3'
#  *************
bringmycar:
    enabled: false
#  *************
supply:
  enabled: false  
#  *************
traefikmetrics:
  enabled: false
#  *************
traefik:
  enabled: true
  source:
    targetRevision: '26.1.0'

#  *************
nfsclient:
  source:
    targetRevision: '4.0.18'
  enabled: false
  nfs:
    path: /home/nfs
    server: 10.0.0.13
  storageClass:
    accessModes : ReadWriteOnce
    defaultClass: false
#  *************
keycloak:
  enabled: false
  destination:
    namespace: keycloak  
  source:
    targetRevision: '19.3.0'
keycloakSecret:
  source:
    directory:
      include: ""
#  *************
cloudnativepg:
  enabled: false
#  *************
postgresexp:
  enabled: false
clustercloudnativepg:
  enabled: false  
#  *************
redpanda:
  enabled: false
  crds:
    source:
      targetRevision: 'v2.1.20-24.1.2'
  operator:
    source:
      targetRevision: '0.4.24'
  cluster:
    clusterSpec:
      console:
        service:
          port: 8080
          type: LoadBalancer
      storage:
        persistentVolume:
          size: 1Gi
      tls:
        enabled: false
